/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Pichau
 */
public class telaConfigurações extends javax.swing.JFrame {

    /**
     * Creates new form telaConfigurações
     */
    public telaConfigurações() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarConfigu = new javax.swing.JButton();
        idade = new javax.swing.JTextArea();
        genero = new javax.swing.JTextArea();
        email = new javax.swing.JTextArea();
        nome = new javax.swing.JTextArea();
        CONFIGURAÇÃO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        voltarConfigu.setBackground(new java.awt.Color(252, 18, 76));
        voltarConfigu.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        voltarConfigu.setForeground(new java.awt.Color(255, 255, 255));
        voltarConfigu.setText("VOLTAR");
        voltarConfigu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltarConfigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarConfiguActionPerformed(evt);
            }
        });
        getContentPane().add(voltarConfigu);
        voltarConfigu.setBounds(170, 660, 90, 30);

        idade.setColumns(20);
        idade.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        idade.setRows(5);
        idade.setBorder(null);
        getContentPane().add(idade);
        idade.setBounds(40, 470, 160, 20);

        genero.setColumns(20);
        genero.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        genero.setRows(5);
        genero.setBorder(null);
        getContentPane().add(genero);
        genero.setBounds(240, 470, 160, 20);

        email.setColumns(20);
        email.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        email.setRows(5);
        email.setBorder(null);
        getContentPane().add(email);
        email.setBounds(40, 590, 350, 20);

        nome.setColumns(20);
        nome.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        nome.setRows(5);
        nome.setBorder(null);
        getContentPane().add(nome);
        nome.setBounds(40, 360, 350, 20);

        CONFIGURAÇÃO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/dra. doramas app/7.png"))); // NOI18N
        getContentPane().add(CONFIGURAÇÃO);
        CONFIGURAÇÃO.setBounds(0, 0, 430, 932);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarConfiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarConfiguActionPerformed
       
    }//GEN-LAST:event_voltarConfiguActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaConfigurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaConfigurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaConfigurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaConfigurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaConfigurações().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONFIGURAÇÃO;
    private javax.swing.JTextArea email;
    private javax.swing.JTextArea genero;
    private javax.swing.JTextArea idade;
    private javax.swing.JTextArea nome;
    private javax.swing.JButton voltarConfigu;
    // End of variables declaration//GEN-END:variables
}
