/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Pichau
 */
public class telaIncial extends javax.swing.JFrame {

    /**
     * Creates new form telaIncial1
     */
    public telaIncial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncomeca = new javax.swing.JButton();
        inicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btncomeca.setBackground(new java.awt.Color(252, 18, 76));
        btncomeca.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btncomeca.setForeground(new java.awt.Color(255, 255, 255));
        btncomeca.setText("COMEÇAR");
        btncomeca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncomeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomecaActionPerformed(evt);
            }
        });
        getContentPane().add(btncomeca);
        btncomeca.setBounds(170, 840, 71, 22);

        inicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/dra. doramas app/1.png"))); // NOI18N
        getContentPane().add(inicial);
        inicial.setBounds(-3, -4, 440, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncomecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomecaActionPerformed
        telaCadastro objTelaCadastro = new telaCadastro();
            objTelaCadastro.setVisible(true);
            dispose();
    }//GEN-LAST:event_btncomecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaIncial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncomeca;
    private javax.swing.JLabel inicial;
    // End of variables declaration//GEN-END:variables
}
